language: ruby

sudo: false

notifications:
  - false

env:
  global:
    - CC_TEST_REPORTER_ID=06e1b464c85d0abe0e620abeda1a00e953d7fb6b7b2b3a1db265757c885bc124

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

before_install: gem install bundler -v 1.16.1

script:
  - bundle exec rspec spec
  - bundle exec rubocop --require rubocop-rspec
